### PR TITLE
Attempt Fixing 404 Page

### LINKED ISSUE #80: 404 breaks in subdirectories.
Basically if I go to http://2003page.ga/invalid 404 works as intended, but in http://2003page.ga/invalid/directory 404 fails to load the assets.

### PR DESCRIPTION
**Pull request by EricZhang456**
Close #80

### CODE REVIEW

**Comment by EricZhang456** [comment]
ahhhhhh

**Comment by EricZhang456** [comment]
screw it, why not just replace everything with http://2003page.ga/file

**Comment by forkiesassds** [comment]
It's not local friendly.

**Comment by EricZhang456** [comment]
No, it doesn't. It still doesn't work for /path/to/file

**Comment by forkiesassds** [comment]
> No, it doesn't. It still doesn't work for /path/to/file

I'm sorry, but I can't run an HTTP server to test this, and if we didn't use GitHub pages then we would be able to fix this in server side.

**Comment by EricZhang456** [comment]
another photo lol

I forked it

**Comment by EricZhang456** [comment]
maybe try /

**Comment by forkiesassds** [comment]
> maybe try /

Seems to be broken in local testing.

**Comment by EricZhang456** [comment]
why not go with another way
create a folder just for 404 and its images, recreate 404.html to make it redirect to the actual 404 page like using `loaction.href` in js

**Comment by EricZhang456** [comment]
sht i just did the stupidest thing in the world

**Comment by EricZhang456** [comment]
let me test it out on my ghp

**Comment by EricZhang456** [comment]
photo

yay it worked

**Comment by EricZhang456** [comment]
oh wait no it doesn't

**Comment by EricZhang456** [comment]
it crashed my broswer

**Comment by EricZhang456** [comment]
I think it is fixed now

**Comment by EricZhang456** [comment]
It works

**Comment by PF94** [comment]
I had to revert this commit cause it was the biggest facepalm moment i've ever saw, not only did it caused infinite-loadings on some cases, it was slow.

**Pull request merged**
