### PR TITLE
2003page's Febuary 2020 Cleanup [part 2 because TLWXPUser]

### PR DESCRIPTION
**Pull request by PF94**
Edited to not look crammed up

This was originaly a cleanup thing

### CODE REVIEW

**Comment by TLWXPUser** [comment]
500 ISSUES WITH "FUCK YOU PF94" ON THEM

**Comment by TLWXPUser** [comment]
wait the labels look like lithuania flag!

**Comment by PF94** [comment]
I think the clean up's done for now.

**Comment by TLWXPUser** [comment]
gey

**Comment by forkiesassds** [comment]
I think you messed something up, It did not clean anything up.

**Comment by TLWXPUser** [comment]
That's why i said gey you uneducated potato

**Comment by TLWXPUser** [comment]
:P

**Comment by PF94** [comment]
> 
> 
> I think you messed something up, It did not clean anything up.

It only deleted unused assets

**Pull request merged**
