### PR TITLE
Introducing a new markdown file: "Don't want"

### PR DESCRIPTION
**Pull request by PF94**
Why? as i begin to notice more and more people want to contribute 2k3page (we got three this quarter!), i want to add some rules to avoid pointless *@##<(@! in 2003page.

### CODE REVIEW

**Comment by TLWXPUser** [comment]
Without Microsoft's Nasty 2008 CSS being cleaned up, our size will keep growing. You will decide our fate, MR.PF94

**Comment by PF94** [comment]
> Without Microsoft's Nasty 2008 CSS being cleaned up, our size will keep growing. You will decide our fate, MR.PF94

ok lol

1. the largest file on this entire website is papa's cheeseria.
2. cleaning up DOESN'T DO ANYTHING, FRONTPAGE WILL OVERWRITE THEM ANYWAYS.

**Comment by TLWXPUser** [comment]
> > Without Microsoft's Nasty 2008 CSS being cleaned up, our size will keep growing. You will decide our fate, MR.PF94
> 
> ok lol
> 
> 1. the largest file on this entire website is papa's cheeseria swf.
> 2. cleaning up DOESN'T DO ANYTHING, FRONTPAGE WILL OVERWRITE THEM ANYWAYS.

It still will happen, also there's frontpage included optimization, also don't mark my comments as off-topic -_- It was related and it was a problem introduced by the "rules" imposed.

**Comment by PF94** [comment]
> 
> 
> > > Without Microsoft's Nasty 2008 CSS being cleaned up, our size will keep growing. You will decide our fate, MR.PF94
> > 
> > 
> > ok lol
> > 
> > 1. the largest file on this entire website is papa's cheeseria swf.
> > 2. cleaning up DOESN'T DO ANYTHING, FRONTPAGE WILL OVERWRITE THEM ANYWAYS.
> 
> It still will happen, also there's frontpage included optimization, also don't mark my comments as off-topic -_- It was related and it was a problem introduced by the "rules" imposed.

we are far from the STORAGE SPACE LIMIT

**Comment by forkiesassds** [comment]
Only use approved editors? Avoid using Javascript, CSS and HTML5 as this can break on older web browsers?

**Pull request merged**
