### PR TITLE
2003page: February 2020 Cleanup

### PR DESCRIPTION
**Pull request by PF94**
This pull request is for a branch that is designed to clean up 2003page and remove unused assets.

### CODE REVIEW

**Comment by forkiesassds** [comment]
I think you supposed to type in 2020 but instead you typed in 2019, I guess we are 1 year behind.

**Comment by PF94** [comment]
> 
> 
> I think you supposed to type in 2020 but instead you typed in 2019, I guess we are 1 year behind.

GODDAMNIT

**Comment by PF94** [comment]
refrain from making pointless reviews that doesnt do anything

**Comment by PF94** [comment]
TLWXPUSER YOU FUCKING PIECE OF ####

**Comment by TLWXPUser** [comment]
uhh
tha

**Comment by TLWXPUser** [comment]
that was unplanned

**Comment by TLWXPUser** [comment]
Anyway's they wouldn't review ¯\_(ツ)_/¯

**Pull request merged**
