### PR TITLE
Standardize pages (except subsites)

### PR DESCRIPTION
**Pull request by EricZhang456**
This will take a while.

To do:

- [x] important
- [x] terminal
- [x] q&a.html
- [x] 404
- [x] 403
- [x] 405
- [x] express limits/index.htm *(might not work on)*
- [x] misc/internet/explorer/start.htm *(will not work on)*
- [x] misc/youtubeplayer/index.html *(HTML 5)*
- [x] misc/promotionalmaterial/sealofapproval/index.htm
- [x] wii/ix.htm
- [x] wii/subsites/index.html
- [x] misc/CONTRIBUTING/index.html *(also update info on the page)*
- [x] misc/azeemEscargot/index.htm

*plus*

- [x] put the fking buttons in a folder

*already standard*

index
misc/index.htm
misc/compatibility/index.html

### CODE REVIEW

**Comment by EricZhang456** [comment]
🤦

**Comment by EricZhang456** [comment]
Damn it, I didn't mark this as ready for review what are you doing here?

**Comment by forkiesassds** [comment]
you asked me for a review

**Comment by forkiesassds** [comment]
What do you mean by standardize?

**Comment by EricZhang456** [comment]
Make it standard HTML, not MSHTML

**Comment by EricZhang456** [comment]
Some versions of NetScape chock hard on MSHTML

**Comment by PF94** [comment]
would the 404 use the mainpage's css, if so, please don't.

**Comment by EricZhang456** [comment]
No it doesn't

**Comment by PF94** [comment]
unassiganed ICTY, which has quit 2003page, and me, who can't be bothered on working on a dying website.

**Comment by EricZhang456** [comment]
who the fked check everything

**Comment by EricZhang456** [comment]
damn i am not bothering #96 for now

**Comment by EricZhang456** [comment]
also: migrated don't want.md into misc/CONTRIBUTING/index.html

**Pull request merged**
