### PR TITLE
merge newhome to master

### PR DESCRIPTION
**Pull request by forkiesassds**
this would cause some issues with buttons and well with the mainpage_rover.css file

### CODE REVIEW

**Comment by EricZhang456** [comment]
Fair

**Comment by EricZhang456** [comment]
is it already done?

**Comment by EricZhang456** [comment]
Seems to be fine

**Comment by EricZhang456** [comment]
Still WIP?

**Comment by forkiesassds** [comment]
nope

**Comment by EricZhang456** [comment]
merge?

**Comment by EricZhang456** [comment]
great

**Pull request merged**
